name: Build and deploy React-admin

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the admin panel to be deployed
    runs-on: ubuntu-latest
    steps:
      # Pull the latest version of the application.
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    name: Deploy React-admin application to Cloudflare
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Deploy artifact to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}